controller_manager
  ros__parameters:

    update_rate: 100

    joint_state_nroadcaster:
      type: joint_state_broadcaster/JointStateBraodcaser

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["fornt_left_wheel_joint", "back_left_whell_joint"]
    right_wheel_names: ["front_right_wheel_joint", "back_right_wheel_joint"]


    


    wheel_separation: 0.2
    wheel_radius: 0.05

    cmd_vel_timeout: 0.5
    publish_rate: 50.0

    odom_frame_id: odom
    base_frame_id: base_link

    enable_odom_fr: true