#ros2_control configuration file

controller_manager:
  ros__parameters:
    update_rate: 100
    position_control:
      type: forward_command_controller/ForwardCommandController
    velocity_control:
      type: forward_command_controller/ForwardCommandController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    sine_controller:
      type: sine_controller/sineController

position_control:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
    interface_name: position
    state_interfaces:
      - position
      - velocity
velocity_control:
  ros__parameters:
    joints:
      - link1_joint
      - link2_joint
    interface_name: velocity
    state_interfaces:
      - position
      - velocity
sine_controller:
  ros__parameters:
    update_rate: 100
    joints:
      - link1_joint
      - link2_joint

